#!/bin/bash

rsync -rvz --progress --exclude-from=/home/jason/public_html/wptest/wp-content/plugins/ucsc-communications-core-functionality-plugin/rsync-exclude.txt ~/public_html/wptest/wp-content/plugins/ucsc-communications-core-functionality-plugin/ ~/public_html/ucsc-communications/wp-content/plugins/ucsc-communications-core-functionality-plugin/